# Generated by Django 5.1.1 on 2024-10-07 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='date',
            new_name='deadline',
        ),
    ]
