# Generated by Django 5.1.1 on 2024-10-08 10:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_rename_date_todo_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date_uploaded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
